### ISSUE TITLE
Only first scope is sent

### ISSUE THREAD

**Issue by moritzgloeckl** [tapkey/tapkey-api-samples-dotnet#1]
Hi,

I'm sending 4 scopes to the Tapkey Authorization Endpoint, however it only recognizes the first one being sent. This seems like a bug, the expected result should be that all scopes are sent to the server.

```
Scopes = new[]
{
"manage:contacts", //only this one is being sent
"manage:grants",
"read:grants",
"read:logs"
}
```

According to the OAuth2.0 specification the scopes are separated by a space char (URL encoded `%20`), I'm positive that Google has this implemented correctly.

Any ideas?

Cheers

**Comment by sebastianhaas** [comment]
Closed via #2
